// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resources/events": {
    params: {};
  };
  "/:eventSlug": {
    params: {
      "eventSlug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resources/events" | "/:eventSlug";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/events-resource.js": {
    id: "routes/events-resource";
    page: "/resources/events";
  };
  "routes/event-detail.jsx": {
    id: "routes/event-detail";
    page: "/:eventSlug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/events-resource": typeof import("./app/routes/events-resource.js");
  "routes/event-detail": typeof import("./app/routes/event-detail.jsx");
};