// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/events/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/events/:id";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/event-detail.jsx": {
    id: "routes/event-detail";
    page: "/events/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/event-detail": typeof import("./app/routes/event-detail.jsx");
};